### PR TITLE
Various build fixes and improvements

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
@perexg not sure if you read your notifications anymore but it would be nice to get this project rolling again. I can take a limited maintainer role if it's okay with you?

**Comment by perexg** [comment]
I hope that I'll reserve some amount of my development time for this project next month to integrate your changes and the WOL changes.

**Comment by Jalle19** [comment]
Awesome! I've noticed that a lot of the currently open issues in this repository are really minisatip issues, and most of them should be closed and referred to minisatip's issue tracker instead. I think improving the README would go along way in guiding users to the right places when they need help.

**Comment by Jalle19** [comment]
@perexg I pushed some more commits that I've been carrying around

**Comment by raindancer2204** [comment]
Hi the last image build was from Sun Oct 21 2018. I also created an issue about implening tvheadend to the system? Is this possible? Is there a planed time for a new release?

**Pull request closed without merging**
